-- Whether someone liked a thing, asked separately from how they'd score it.
--
-- The rating column can only answer that by way of a number, and a number is
-- exactly what people skip: "I finished this and it wasn't for me" is a common
-- thing to want to record and an uncomfortable thing to have to put 0.5 stars
-- on. Status can't answer it either — status is where you are with something
-- (want it, partway, done), and liking it is orthogonal to all three.
--
-- Three states, so null is a real value here rather than an absence to paper
-- over: true liked, false didn't, null hasn't said. Nothing is backfilled — an
-- existing rating is a score, not a verdict, and inferring "disliked" from a
-- low one would be putting words in people's mouths. It stays null until asked.
alter table user_media_interactions add column liked boolean;
