import { pool } from '../db.ts'
import type { MediaType } from '../mediaItems.ts'
import type { User } from '../schema.ts'
import { LIMIT_WINDOW_MS } from './dailyLimit.ts'

// One roll a day, on the same rolling 24-hour window the run and rebuild caps
// use. A calendar day would need a timezone this app doesn't collect — the
// server's clock is UTC — and would hand someone rolling at 23:50 another go ten
// minutes later.
export const LUCKY_WINDOW_MS = LIMIT_WINDOW_MS

// Lucky runs are named, so they read as themselves in the list of past runs
// rather than as an unnamed one-pick run somebody generated by accident.
export const LUCKY_RUN_NAME = 'Lucky pick'

// What "today's pick" is, everywhere it's shown: the landing page, the profile,
// and the panel the button lives in.
export interface LuckyPick {
  runId: number
  mediaItemId: number
  mediaType: MediaType
  title: string
  metadata: unknown
  reason: string
  createdAt: number
  // Everyone in the run other than the person it belongs to. Empty for a solo
  // roll.
  otherMemberLabels: string[]
}

export interface LuckyState {
  // Null until the first roll of the window. The button and the card are two
  // views of this one field: a pick means "here's today's", none means "go".
  pick: LuckyPick | null
  available: boolean
  // When the next roll frees up. Null whenever one is available now.
  nextAt: number | null
}

interface LuckyRow {
  run_id: number
  media_item_id: number
  media_type: MediaType
  title: string
  metadata: unknown
  reason: string
  created_at: string | number
  other_members: string[] | null
}

// The whole card in one query — this runs on the landing page, which otherwise
// touches the database only to identify the visitor.
//
// Joined rather than left-joined to user_recommendations on purpose: a lucky run
// that came back with nothing (every candidate dropped by the gates) matches no
// row here, so it neither shows as today's pick nor spends the day. There is
// nothing to show for it, and the point of the feature is that a click produces
// something.
//
// `rank asc` with `limit 1` rather than an assumption of one row: a lucky run
// carries a single pick today, and this stays correct if that ever changes.
async function findLuckyPick(userId: number, since: number): Promise<LuckyPick | null> {
  const { rows } = await pool.query<LuckyRow>(
    `select r.id as run_id, r.media_type, r.created_at,
            ur.media_item_id, ur.reason,
            m.title, m.metadata,
            (select array_agg(coalesce(nullif(u.display_name, ''), u.email) order by u.display_name)
               from recommendation_run_members rm
               join users u on u.id = rm.user_id
              where rm.run_id = r.id and rm.user_id <> r.user_id) as other_members
       from recommendation_runs r
       join user_recommendations ur on ur.run_id = r.id
       join media_items m on m.id = ur.media_item_id
      where r.user_id = $1 and r.is_lucky and r.created_at >= $2
      order by r.created_at desc, ur.rank asc
      limit 1`,
    [userId, since],
  )

  const row = rows[0]
  if (!row) return null

  return {
    runId: row.run_id,
    mediaItemId: row.media_item_id,
    mediaType: row.media_type,
    title: row.title,
    metadata: row.metadata,
    reason: row.reason,
    createdAt: Number(row.created_at),
    otherMemberLabels: row.other_members ?? [],
  }
}

// Admins are exempt from the cap, the same way they are exempt from the run and
// rebuild caps — see dailyLimit.ts. They still see their latest pick.
export async function getLuckyState(user: User, now: number = Date.now()): Promise<LuckyState> {
  const pick = await findLuckyPick(user.id, now - LUCKY_WINDOW_MS)
  const available = pick == null || user.is_admin

  return {
    pick,
    available,
    nextAt: available || pick == null ? null : pick.createdAt + LUCKY_WINDOW_MS,
  }
}
